apiVersion: v1
kind: Service
metadata:
  labels:
    app: fastapi-app
  name: fastapi-app
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.103.146.172
  clusterIPs:
  - 10.103.146.172
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30602
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: fastapi-app
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
