apiVersion: v1
kind: Service
metadata:
  labels:
    app: fastapi-app
  name: fastapi-app
  namespace: default
spec:
  type: {{ .Values.service.type }}
  selector:
    app: fastapi-app
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP